PortfolioWebsite/Controllers/ParkingSensorsController.cs
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using DataAccess.GeoCoding;
using DataAccess.MelbourneDataPortal.ParkingSensors;
using DataAccess.MelbourneDataPortal.ParkingSensors.Model;

namespace MelbourneData.Controllers
{
    public class ParkingSensorsController : Controller
    {
        private static List<ParkingData> _data = new List<ParkingData>();
        private List<ParkingData> _model = new List<ParkingData>();
        private static ParkingData _currentData = new ParkingData();

        [HttpGet]
        public ActionResult ParkingSensors()
        {
            return View(_model);
        }

        [HttpGet]
        public ActionResult Refresh()
        {
            _data = ParkingDataAccess.GetDataSet(ConfigurationManager.AppSettings["ParkingSensorsDataset"],
                ConfigurationManager.AppSettings["CityOfMelbourneKey"]).Values.ToList();
            _model = _data;

            var occupiedBays = _model.Count(x => x.Status.Equals("Present"));
            var unOccupiedBays = _model.Count(x => x.Status.Equals("Unoccupied"));

            ViewData.Add("occupiedBays", occupiedBays);
            ViewData.Add("UnOccupiedBays", unOccupiedBays);

            return PartialView("ParkingListPartial", _model);
        }

        [HttpGet]
        public ActionResult ParkingSpotDetail(int bayid)
        {
            _currentData = _data.FirstOrDefault(x => x.BayId == bayid);
            ViewData.Add("mapimage", MapUrlGenerator(_currentData.Lat, _currentData.Lon, ConfigurationManager.AppSettings["GoogleGeoCodingKey"]));

            var geocodingresult = Geocoding.GETAsync(_currentData.Lat, _currentData.Lon).Result.results.First();

            _currentData.Address = geocodingresult.formatted_address;

            return View(_currentData);
        }

        private string MapUrlGenerator(double lat, double lon, string key)
        {
            return "https://maps.googleapis.com/maps/api/staticmap?center=melbourne,victoria&zoom=14&size=600x600&maptype=roadmap&markers=color:blue%7clabel:s%7c" + lat + "," + lon + "&key=" + key;
        }
    }
}

PortfolioWebsite/Views/ParkingSensors/ParkingListPartial.cshtml
@using DataAccess.MelbourneDataPortal.ParkingSensors.Model
@model List<ParkingData>

@{
    ViewBag.Title = "title";
    Layout = "";
}

<h1>Search results</h1>
<p>Number of free car spots = @ViewData["UnOccupiedBays"]</p>
<input type="text" id="SearchParking" onkeyup="search()" placeholder="Search for bayid.." title="Type in a bay id" />
<table id="Parking" class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().BayId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Lat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Lon)
        </th>
        <th></th>
    </tr>

    @foreach (ParkingData item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BayId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lon)
            </td>
            <td>
                @Html.ActionLink("Details", "ParkingSpotDetail", new { bayId = item.BayId })
            </td>
        </tr>
    }
</table>

<script>
    function search() {
        var td, i;
        var input = document.getElementById("SearchParking");
        var filter = input.value.toUpperCase();
        var table = document.getElementById("Parking");
        var tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }

    }

</script>

PortfolioWebsite/Views/ParkingSensors/ParkingSensors.cshtml
@model System.Collections.Generic.List<DataAccess.MelbourneDataPortal.ParkingSensors.Model.ParkingData>

@{
    ViewBag.Title = "Parking Sensors";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<p>
    Contains information from in-ground car parking bay sensors across the city with status indicating if a car is present or not present, the spatial coordinate of the sensor, and the street marker id.
</p>

<p>please note - 	Parking Sensors are not operational on Public Holidays. Parking Sensors will show car parks as vacant when blocked by construction zones. </p>
<div>
    <div class="parkingButtonContainer">

        <input type="button" id="btnClick" class="parkingButton" value="Refresh" />
        <input type="button" id="btnHide" class="parkingButton" value="Hide Table" />

    </div>
    <div id="ParkingData"></div>

</div>

@Scripts.Render("~/bundles/jquery")
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<script>
   $('#btnClick').click(function () {
       $('#ParkingData').show();
        $.get('@Url.Action("Refresh", "ParkingSensors")', {}, function (model) {
            $("#ParkingData").html(model);
        });
    });
    $('#btnHide').click(function () {
        $('#ParkingData').hide();
    });
</script>

PortfolioWebsite/Views/ParkingSensors/ParkingSpotDetail.cshtml
@model DataAccess.MelbourneDataPortal.ParkingSensors.Model.ParkingData

@{
    ViewBag.Title = "ParkingSpotDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="column"><h2>ParkingSpotDeatail</h2></div>
    <div class="column"><h5><a href="javascript:void(0);" onclick="history.go(-1);">Back to Details</a></h5></div>
</div>

<p>Street address = @Model.Address</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BayId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lon)
        </th>
        <th></th>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(modelItem => Model.BayId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Lat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.Lon)
        </td>
    </tr>
</table>

<img src="@ViewData["mapImage"]" alt="Parking location on map" />

<script type="text/javascript">
    $(document).on('click', '#backLink', function () {
        history.go(-1);
    });
</script>