PortfolioWebsite/Controllers/BikeShareController.cs
using System.Web.Mvc;
using DataAccess.MelbourneDataPortal.MelbourneBikeShare.Model;
using DataAccess.MelbourneDataPortal.MelbourneBikeShare;
using System.Configuration;
using System.Collections.Generic;
using System.Linq;

namespace MelbourneData.Controllers
{
    public class BikeShareController : Controller
    {
        private static List<BikeShareData> _model = new List<BikeShareData>();

        [HttpGet]
        public ActionResult BikeShare()
        {
            _model = BikeShareDataAccess.GetDataSet(ConfigurationManager.AppSettings["BikeShareDataset"],
                ConfigurationManager.AppSettings["CityOfMelbourneKey"]).Values.ToList();

            return View(_model);
        }

        [HttpGet]
        public ActionResult GetParkingInfo()
        {
            int BayId = 10;
            BikeShareData _data = _model.Find(item => item.BayId == BayId);
            return PartialView("BikeShareDetailsPartial", _data);
        }
    }
}

PortfolioWebsite/Views/BikeShare/BikeShare.cshtml
@model System.Collections.Generic.List<DataAccess.MelbourneDataPortal.MelbourneBikeShare.Model.BikeShareData>

@{
    ViewBag.Title = "Melbourne Bike Share";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Melbourne Bike Share</h2>
<body>
    <br />
    <div id="map"></div>
    <div id="ParkingData"></div>

    <script>
        function initMap() {

            var broadway = {
                info: '<strong>Chipotle on Broadway</strong><br>\
					5224 N Broadway St<br> Chicago, IL 60640<br>\
					<a href="https://goo.gl/maps/jKNEDz4SyyH2">Get Directions</a>',
                lat: 41.976816,
                long: -87.659916
            };

            var belmont = {
                info: '<strong>Chipotle on Belmont</strong><br>\
					1025 W Belmont Ave<br> Chicago, IL 60657<br>\
					<a href="https://goo.gl/maps/PHfsWTvgKa92">Get Directions</a>',
                lat: 41.939670,
                long: -87.655167
            };

            var sheridan = {
                info: '<strong>Chipotle on Sheridan</strong><br>\r\
					6600 N Sheridan Rd<br> Chicago, IL 60626<br>\
					<a href="https://goo.gl/maps/QGUrqZPsYp92">Get Directions</a>',
                lat: 42.002707,
                long: -87.661236
            };

            var locations = [
                [broadway.info, broadway.lat, broadway.long, 0],
                [belmont.info, belmont.lat, belmont.long, 1],
                [sheridan.info, sheridan.lat, sheridan.long, 2],
            ];

            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 13,
                center: new google.maps.LatLng(41.976816, -87.659916),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });

            var infowindow = new google.maps.InfoWindow({});

            var marker, i;

            for (i = 0; i < locations.length; i++) {
                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                    map: map
                });

                google.maps.event.addListener(marker, 'click', (function (marker, i) {
                    return function () {
                        infowindow.setContent(locations[i][0]);
                        infowindow.open(map, marker);
                        $.get('@Url.Action("GetParkingInfo", "BikeShare")', {}, function (model) {
                                    $("#ParkingData").html(model);
                        })
                    }
                })(marker, i));
            }
        }

    </script>

    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDklNWhszRKRIj_KOFO_5-xGQs-CeoRdoI&callback=initMap">
    </script>

</body>

PortfolioWebsite/Views/BikeShare/BikeShareDetailsPartial.cshtml
@model DataAccess.MelbourneDataPortal.MelbourneBikeShare.Model.BikeShareData

<div>
    <h4>BikeShareData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BayId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BayId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Featurename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Featurename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coordinates)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coordinates)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TerminalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TerminalName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NBBikes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NBBikes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NBEmptydoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NBEmptydoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UploadDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UploadDate)
        </dd>

    </dl>
</div>